# Site settings

title: recipes.mpdavis.com
author: Michael Davis
email: michael@mpdavis.com
description: Recipes worth saving.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recipes.mpdavis.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mpdavis

# Theme settings
theme: minima
# The skins option isn't available until Minima v3.0, but v2.5 is the last official release
#minima:
#  skin: solarized-dark

# Collections
collections:
  recipes:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
