# Site settings

title: Michael Davis
author:
  name: Michael Davis
  email: michael@mpdavis.com
  github: mpdavis
email: michael@mpdavis.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mpdavis.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mpdavis

plugins:
  - jekyll-figure

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _recipes/TEMPLATE.md

# Theme settings
theme: minima
minima:
  skin: classic
  social_links:
    - { platform: github,         user_url: "https://github.com/mpdavis/" }

# Collections
collections:
  recipes:
    output: true
